version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: buskr_postgres
    environment:
      POSTGRES_USER: buskr
      POSTGRES_PASSWORD: buskr
      POSTGRES_DB: buskr
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  

  redis:
    image: redis:7-alpine
    container_name: buskr_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: